CREATE DATABASE COMPUTER

USE COMPUTER

SELECT [NAME], [ADDRESS], [SPECIFICATIONSID], [CONSIGMENTID] FROM MANUFACTURER, SPECIFICATIONS WHERE[ADDRESS] = 'Богодухов' AND FREQUENCY = (SELECT MAX(FREQUENCY) FROM SPECIFICATIONS)

CREATE TABLE DISTRIBUTOR
(
	ID				INT PRIMARY KEY IDENTITY (0,1),
	[NAME]			NVARCHAR(MAX) NOT NULL,
	[ADDRESS]		NVARCHAR(MAX) NOT NULL,
	[PHONE]			NVARCHAR(MAX) NOT NULL
)
GO

CREATE TABLE SPECIFICATIONS
(
	[MANUFACTURERID] INT IDENTITY (0,1),
	[MODEL]			 NVARCHAR(MAX) NOT NULL,
	[CPU]			 NVARCHAR(MAX) NOT NULL,
	[FREQUENCY]		 INT		   NOT NULL,
	[RAM]			 INT		   NOT NULL,
	[HardDiskSpace]  INT		   NOT NULL,
	[RELEASEdATE]	 DATETIME	   NOT NULL,
	CONSTRAINT PC_MANUFACTURER PRIMARY KEY ([MANUFACTURERID])
)
GO


CREATE TABLE CONSIGNMENT
(
	[IDCONSIGMENT]	 INT IDENTITY (0,1),
	[BATCHSIZE]		 INT NOT NULL,
	[PRICE]			 INT NOT NULL,
	CONSTRAINT PK_CONSIGMENT PRIMARY KEY ([IDCONSIGMENT])
)
GO

CREATE TABLE MANUFACTURER
(
	[IDMANUFACTURER]	INT IDENTITY (0,1), 
	[NAME]				NVARCHAR(MAX) NOT NULL,
	[ADDRESS]			NVARCHAR(MAX) NOT NULL,
	[SPECIFICATIONSID]	INT CONSTRAINT FK_MANUFACTURER_SPECIFICATIONS FOREIGN KEY REFERENCES SPECIFICATIONS ([MANUFACTURERID]),
	[CONSIGMENTID]		INT CONSTRAINT FK_MANUFACTURER_CONSIGMENT	  FOREIGN KEY REFERENCES CONSIGNMENT    ([IDCONSIGMENT]),
	CONSTRAINT PK_MANUFACTUR PRIMARY KEY  ([IDMANUFACTURER])
)
GO
drop table MANUFACTURER, CONSIGNMENT, SPECIFICATIONS, DISTRIBUTOR
